### ISSUE TITLE
Screenshots of Centrepoint app

### ISSUE THREAD

**Issue by msachi** [lucy-marko/centrepoint#36]
<img width="332" alt="landing-page" src="https://cloud.githubusercontent.com/assets/17763838/22792191/daabde58-eee3-11e6-91a9-b0012823b2ab.png">

<img width="330" alt="info-page" src="https://cloud.githubusercontent.com/assets/17763838/22792198/e06c6b64-eee3-11e6-8745-50275f473d52.png">

**Comment by Hafsahfg** [comment]
Hi guys... looking good!

**Comment by msachi** [comment]
@Hafsahfg This the final page

<img width="334" alt="submit-page" src="https://cloud.githubusercontent.com/assets/17763838/22826560/074c8c4e-ef8b-11e6-9dfc-d99d3ac257ab.png">

**Comment by Hafsahfg** [comment]
this looks great :-)

**Comment by Hafsahfg** [comment]
alternative copy for welcome page:

WELCOME!

You can use this app to request information from when you were at Centrepoint:

- address history
- rent arrears report
- rental reference 

First step - log in using YOTI so we can check you are who you say you are!

(LOG IN WITH YOTI)
