### ISSUE TITLE
Console.log(form data)

### ISSUE THREAD

**Issue by lucymonie** [lucy-marko/centrepoint#43]
Add functionality to retrieve form data and user profile and email as request for information to Centrepoint. Stretch goal.

**Comment by msachi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Retrieve form data](https://trello.com/c/LmJp0SlF/5-retrieve-form-data)

**Comment by lucymonie** [comment]
Possible resources:
- https://github.com/dwyl/html-form-send-email-via-google-script-without-server
- https://nodemailer.com/about/
- https://github.com/dwyl/sendemail-gmail
