### ISSUE TITLE
Alternative login link on front page

### ISSUE THREAD

**Issue by lucymonie** [lucy-marko/centrepoint#50]
We added a link to the Centrepoint home page as an 'alternative login' but this is meaningless and potentially would throw people off and annoy them.

Should we just remove this altogether, or is there an alternative method of contact we could direct people to use? How prominent should this be?

**Comment by lucymonie** [comment]
We discussed this on the phone and agreed that we would remove this link from the front page altogether.

**Comment by Hafsahfg** [comment]
@lucymonie as long as there is something on the YOTI page that explains what YOTI is or how to sign up then I agree it's ok to remove
