### ISSUE TITLE
Redirection not working on mobile

### ISSUE THREAD

**Issue by msachi** [lucy-marko/centrepoint#57]
On mobile, the 'Log in with Yoti' button redirects to the Yoti app fine, but once the user has authorized Yoti they get stuck there. Yoti doesn't seem to get the browser to redirect to the callback url.

On desktop, redirection from the app to Yoti and back works as expected.

**Comment by Alttaf** [comment]
can you include some screen shots and the url as displayed in the yoti dashboard please

**Comment by msachi** [comment]
Thanks @Alttaf! I've sent you screenshots of the Yoti dashboard by e-mail. The callback url is https://centrepoint-alumni.herokuapp.com/info

@lucymonie Could you send us a screenshot of the app when it gets stuck? I can't actually get to that stage because I can't get my passport to be Yoti-approved.

**Comment by lucymonie** [comment]
![img_4672](https://cloud.githubusercontent.com/assets/16781258/23030647/4063e5ba-f466-11e6-92ad-66971c12e618.PNG)

![img_4669](https://cloud.githubusercontent.com/assets/16781258/23030638/38e8d8ae-f466-11e6-993f-c0e74014815b.PNG)
Sure thing. Here the sequence:
![img_4667](https://cloud.githubusercontent.com/assets/16781258/23030603/2473ebb6-f466-11e6-913d-8be0ca3783be.PNG)
![img_4668](https://cloud.githubusercontent.com/assets/16781258/23030616/2abb513a-f466-11e6-8818-554d1512987a.PNG)

**Comment by lucymonie** [comment]
I took some screenshots on my phone and they are huge! I will post them here:
<div style="width:100px; height: auto;"><img style="max-height:100%; max-width:100%; object-fit: contain;" src="https://cloud.githubusercontent.com/assets/16781258/23030956/3d38878c-f467-11e6-8eca-a26d124cf104.PNG" /></div>

**Comment by lucymonie** [comment]
![img_4668](https://cloud.githubusercontent.com/assets/16781258/23030984/53927506-f467-11e6-85f8-932ad0360dba.PNG)

**Comment by lucymonie** [comment]
![img_4669](https://cloud.githubusercontent.com/assets/16781258/23030997/5e9c06ba-f467-11e6-9b05-00f4d2aea4f7.PNG)

**Comment by lucymonie** [comment]
After I click on 'ALLOW' I see the following screen:
![img_4672](https://cloud.githubusercontent.com/assets/16781258/23031029/763e6a7e-f467-11e6-80ed-2057d5fa2764.PNG)

**Comment by lucymonie** [comment]
And nothing else happens after this.

**Comment by Alttaf** [comment]
Thanks @lucymonie we are still trying to reproduce, can you post the device information here i.e. which phone, which browser etc

**Comment by rusuOana** [comment]
Hi all, we are trying to reproduce the problem, but when I go to the callbackurl: https://centrepoint-alumni.herokuapp.com/info, I get an error

 {
"statusCode": 500,
"error": "Internal Server Error",
"message": "An internal server error occurred"
}

Is this expected?

**Comment by msachi** [comment]
@Alttaf It was iPhone 5S, using Chrome.

@rusuOana The reason for the server error is that the info route expects a token to parse, and won't work without a token. Apologies but we're not handling errors properly at the moment. You could try adding a fake token manually to the url?

**Comment by msachi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Solve mobile redirection](https://trello.com/c/t8wM4p8c/3-solve-mobile-redirection)

**Comment by msachi** [comment]
@Alttaf and @rusuOana I was wondering if you've made any progress with this? We would like to get it working in the next couple of weeks so that we have a working prototype to test. Thanks!

**Comment by rusuOana** [comment]
Sorry, it was a crazy period. We tried it on a few phones, but could not reproduce (iphones 6s). it's always really hard to get a production account, (i will have to delete the one I have to be able to try it on a new phone). I will try to get someone with an iPhone 5 to try and help me reproduce the problem. Is that right or should I try with other phones as well?

**Comment by msachi** [comment]
@rusuOana No worries, and thanks for looking into it! It is quite important for us that the app works across most smartphones, because many of our users won't have the newest smartphones.

Would it be okay if @lucymonie and I come over to your offices one day? We could reproduce the problem on our phones, show you our Heroku settings (in case it's a deployment issue), and work through the problem together. We could probably do most days, whenever is best for you?

**Comment by rusuOana** [comment]
That is a good idea, but I would really like to be able to reproduce it, so I know which team should look into this, as it is a joined effort, so I wouldn't like to make you guys come over just to see how we can reproduce it, I will need to investigate it (ask people to investigate it) and see which team should fix this.

**Comment by msachi** [comment]
@rusuOana Something that we forgot to mention is that the redirect sometimes appeared to work on mobile internet (3G/4G) but not on wifi, in case that helps with pinpointing the issue.

**Comment by msachi** [comment]
Also, another phone that we tested the redirect on and it wasn't working is Motorola (Moto E 2nd generation, Android 5.0.2).

**Comment by msachi** [comment]
We tested this on an iPhone 6 and it wasn't working on it either. The mobile / wifi connection doesn't actually seem to make a difference.

**Comment by rusuOana** [comment]
Sorry for the delay..I've been away and we are in the middle of the release this days. By the end of the week I should be able to have time to work on this, might be a bit hard to get production apps on different phones, but I will do what I can and let you know as soon as I can!

**Comment by rusuOana** [comment]
hi @msachi I wanted to look now at the problem to try to get to the bottom of this. When I access  https://centrepoint-alumni.herokuapp.com/info, I get "nothing here, yet". can you tell me what I do wrong please?:)

**Comment by rusuOana** [comment]
On my iPhone 6, I went to 
1. http://childline-report-image.herokuapp.com, 
2. clicked on login with yoti,
3. got redirected to the yoti app
4. clicked allow
5. got redirected to the web page to the screen attached. 

The callback url is 
https://childline-report-image.herokuapp.com/thankyou?token=bs4gwJLIODoAdP76tpaJ9NG0Hu7LEn-3A1znoiO5L2mjwtUz_TaE2_UKtsZ-S40lTwT5dn7C6ayJo0ufzMdLJol292S2s7RQzkg6NmHouHNK9M-UjOSVA-KvbRdV-eB3J_49pHZ8_5d9M-QaRQo-_YY82W_m2MxprRdLaA_KMBugWwNSsPzF5FIF2fLk2yl4E2jjMiC8YWnSjQN6XpGzUho7PPxg7UDgAB5ktGZo00e19y9rgrD_Ja3HENwhqZyRx44eo0EqDSaKcWcqR01gMQUaHhu6kVhBaZjTrNVaCnob7XIIu17-z6HWa6HgFth8z9nyyIdYDwvzM_-qKA4ycA==

@msachi did someone updated the callback url in the meantime, since you reported the issue? As if I look the comments above, the callback url seems to be different

**Comment by rusuOana** [comment]
![img_3548](https://cloud.githubusercontent.com/assets/14177433/24216053/b8d43720-0f32-11e7-9d41-45de97d5a73b.PNG)

**Comment by rusuOana** [comment]
@msachi see previous comment + we also tried on a Nexus 5, and the same flow works, except the part that the callback url shows a 404 (because the way the url is build by us, which might be a bug, but a different one). From what we tried tonight, the redirect works. Is it possible to try again with the latest Yoti apps and let us know if the issue reported still happens?

@msachi can you please let us know what is the callback url set to?
Does it have in the end a "/" or not?

**Comment by msachi** [comment]
@rusuOana The app that you are looking at is not our app!

Ours is available at https://centrepoint.herokuapp.com/
The callback url is set to either https://localhost:9443/login (for development purposes) or https://centrepoint.herokuapp.com/login (for production).
Please can you try it again with our app.

**Comment by rusuOana** [comment]
Ok, massive confusion then I guess...we had an issue raised, that points to this github thread, but that had reported as a main url the one I tried yesterday...

I tried with https://centrepoint.herokuapp.com/, and after I click Allow on mobile app, I am not redirected. I will get back to you after we tried more times and figured out what is going on.

**Comment by msachi** [comment]
Hi, I'm not sure - perhaps the other team have pointed you to our issue because they have the same problem.

Yes, this is exactly the problem that we are experiencing.

**Comment by cquemin** [comment]
Your callback is set to https://localhost:9443/login, in Safari (on iOS) this is not considered as a valid host and therefore fails when the mobile app tries to invoke it. It is most likely the case for other browser.
I would suggest to set it to something different ( it could be the actual IP of the machine you are trying to reach) I believe that should help. 
But from the phone perspective localhost is the phone itself, so I am not quite sure how you would validate the implementation if the callback URL is not set to real host that the mobile device can reach? Or am I missing something ?

**Comment by lucymonie** [comment]
Hi @cquemin, thanks for the message. Just to clarify, we have (at times) had our Yoti dashboard set to redirect to https://localhost:9443/login so we can view local changes during development. However, we changed the redirect to https://centrepoint.herokuapp.com/login since yesterday so that you could test it. Perhaps have another try and see how you go. 

Just to make absolutely sure we are looking at the same thing, the url for our app is:
https://centrepoint.herokuapp.com

**Comment by msachi** [comment]
This appears to have been fixed now 🎉 🎉
