### ISSUE TITLE
Add an easy way of making someone an admin

### ISSUE THREAD

**Issue by msachi** [lucy-marko/centrepoint#70]
e.g. existing admins can add new admins

**Comment by lucymonie** [comment]
We need a way to identify people who are to be set as admin in the database, and we concluded that asking them to enter their phone number is a good way of uniquely identifying a user.  So this means there are a few new tasks:
- [x] Add a helper to format phone numbers correctly before they go into the database (at the moment they go in with '44' at the start and no '0'
- [x] Add a helper to remove any spaces from the mobile number
- [x] Add a field to the form that requests their mobile number when they are to be added as an admin
- [x] Update the database query to include a check of the phone number
- [x] Tidy up formatting of input fields on add new admin form so fields are stacked
