### ISSUE TITLE
Connect submitted form data with database

### ISSUE THREAD

**Issue by lucymonie** [lucy-marko/centrepoint#99]
Create queries to transfer requests and users into the database.

This is a point where we should validate inputs and whitelist certain types of inputs:
https://www.owasp.org/index.php/Testing_for_Input_Validation
https://www.owasp.org/index.php/Input_Validation_Cheat_Sheet
http://codereview.stackexchange.com/questions/30237/form-validation-security-and-input-specification

**Comment by msachi** [comment]
- [x] Store users (Yoti data)
- [x] Store requests (form data)
